name: Build and Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/main' || github.ref_type == 'tag'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Get tag name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package -Drevision=${{ env.VERSION }}

      - name: Prepare artifact
        run: |
          cp target/gportal-query-${{ env.VERSION }}.jar target/gportal-query-plugin.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gportal-query-${{env.VERSION}}.jar
          path: target/gportal-query-plugin.jar
